package com.sec.internal.google;

import android.media.AudioFormat;
import android.media.AudioRecord;
import android.media.MediaCodec;
import android.media.MediaFormat;
import android.media.MediaRecorder;
import android.os.SystemClock;
import android.os.SystemProperties;
import android.util.Log;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.nio.ByteBuffer;
import java.security.SecureRandom;
import java.util.concurrent.atomic.AtomicBoolean;

final class ApRtpUplinkPoc {
 private static final String TAG="AP_UPLINK_RTP";
 private final DatagramSocket socket;private final InetAddress address;private final int port,pt,dtmfPt,dtmfClock;private final long ssrc;private final boolean amrNb;private final int sampleRate,timestampStep,bitRate;private final String codecMime;private final long[] ftCounts=new long[16];private final Object sendLock=new Object(),dtmfLock=new Object();private final AtomicBoolean running=new AtomicBoolean(true),stopStarted=new AtomicBoolean(false);private volatile AudioRecord record;private volatile MediaCodec codec;private volatile Thread thread,dtmfThread,pulseThread;private int seq;private long timestamp;private long packets,bytes,errors,pcmBytes,encodedFrames,dtmfPackets,dtmfErrors;private int dtmfEvent=-1;private boolean dtmfStop;private boolean marker=true;
 ApRtpUplinkPoc(DatagramSocket s,InetAddress a,int p,int payload,long sender,boolean nb){socket=s;address=a;port=p;if(payload<0||payload>127)throw new IllegalArgumentException("uplink pt="+payload);pt=payload;ssrc=sender;amrNb=nb;sampleRate=nb?8000:16000;timestampStep=nb?160:320;bitRate=ApMediaConfigPoc.uplinkBitrate(nb);dtmfPt=ApMediaConfigPoc.dtmfPt(nb);dtmfClock=sampleRate;codecMime=nb?"audio/3gpp":"audio/amr-wb";SecureRandom r=new SecureRandom();seq=r.nextInt()&0xffff;timestamp=r.nextInt()&0xffffffffL;}
 void start(){thread=new Thread(new MainRunner(this),"ap-amrwb-uplink");thread.setDaemon(true);thread.start();}
 private static final class MainRunner implements Runnable{final ApRtpUplinkPoc owner;MainRunner(ApRtpUplinkPoc o){owner=o;}public void run(){owner.run();}}
 void stop(String why){if(stopStarted.compareAndSet(false,true)){running.set(false);synchronized(dtmfLock){dtmfStop=true;dtmfLock.notifyAll();}AudioRecord r=record;if(r!=null)try{r.stop();}catch(Throwable ignored){}Thread p=pulseThread;if(p!=null)p.interrupt();boolean mainStopped=await(thread,1500);boolean dtmfStopped=await(dtmfThread,1500);boolean pulseStopped=await(p,500);if(!mainStopped){Thread t=thread;if(t!=null)t.interrupt();mainStopped=await(t,1500);}if(!dtmfStopped){Thread t=dtmfThread;if(t!=null)t.interrupt();synchronized(dtmfLock){dtmfLock.notifyAll();}dtmfStopped=await(t,1000);}if(!pulseStopped){if(p!=null)p.interrupt();pulseStopped=await(p,500);}Log.i(TAG,"STOP_REQUEST reason="+why+" mainStopped="+mainStopped+" dtmfStopped="+dtmfStopped+" pulseStopped="+pulseStopped+" recordReleased="+(record==null)+" codecReleased="+(codec==null));}}
 private static boolean await(Thread t,long ms){if(t==null||t==Thread.currentThread())return true;try{t.join(ms);}catch(InterruptedException e){Thread.currentThread().interrupt();}return !t.isAlive();}
 private static int source(String s){if("mic".equals(s))return MediaRecorder.AudioSource.MIC;if("voice_communication".equals(s))return MediaRecorder.AudioSource.VOICE_COMMUNICATION;if("voice_uplink".equals(s))return MediaRecorder.AudioSource.VOICE_UPLINK;return -1;}
 private static boolean validNbBitrate(int v){return v==4750||v==5150||v==5900||v==6700||v==7400||v==7950||v==10200||v==12200;}
 private static String distribution(long[] counts){StringBuilder s=new StringBuilder();for(int i=0;i<counts.length;i++)if(counts[i]!=0){if(s.length()!=0)s.append(',');s.append(i).append(':').append(counts[i]);}return s.length()==0?"none":s.toString();}
 private int bits(int ft){if(amrNb){switch(ft){case 0:return 95;case 1:return 103;case 2:return 118;case 3:return 134;case 4:return 148;case 5:return 159;case 6:return 204;case 7:return 244;case 8:return 39;default:throw new IllegalArgumentException("unsupported AMR-NB FT="+ft);}}switch(ft){case 0:return 132;case 1:return 177;case 2:return 253;case 3:return 285;case 4:return 317;case 5:return 365;case 6:return 397;case 7:return 461;case 8:return 477;case 9:return 40;default:throw new IllegalArgumentException("unsupported AMR-WB FT="+ft);}}
 private static int bit(byte[] b,int n){return(b[n>>3]>>(7-(n&7)))&1;}
 private static void setBit(byte[] b,int n,int v){if(v!=0)b[n>>3]|=(byte)(0x80>>(n&7));}
 boolean isVoiceActive(){Thread t=thread;return running.get()&&t!=null&&t.isAlive()&&socket!=null&&!socket.isClosed();}
 boolean startDtmf(int event){if(event<0||event>15||!isVoiceActive())return false;synchronized(dtmfLock){if(dtmfEvent>=0)return false;dtmfEvent=event;dtmfStop=false;dtmfThread=new Thread(new DtmfRunner(this,event),"ap-dtmf-rtp");dtmfThread.setDaemon(true);dtmfThread.start();return true;}}
 boolean stopDtmf(){synchronized(dtmfLock){if(dtmfEvent<0)return false;dtmfStop=true;dtmfLock.notifyAll();return true;}}
 boolean pulseDtmf(int event){if(!startDtmf(event))return false;synchronized(dtmfLock){Thread old=pulseThread;if(old!=null)old.interrupt();pulseThread=new Thread(new PulseStopper(this),"ap-dtmf-pulse");pulseThread.setDaemon(true);pulseThread.start();return true;}}
 private static final class DtmfRunner implements Runnable{final ApRtpUplinkPoc owner;final int event;DtmfRunner(ApRtpUplinkPoc o,int e){owner=o;event=e;}public void run(){owner.runDtmf(event);}}
 private static final class PulseStopper implements Runnable{final ApRtpUplinkPoc owner;PulseStopper(ApRtpUplinkPoc o){owner=o;}public void run(){try{Thread.sleep(160);if(owner.running.get())owner.stopDtmf();}catch(InterruptedException ignored){}finally{if(owner.pulseThread==Thread.currentThread())owner.pulseThread=null;}}}
 private void runDtmf(int event){int eventPt=dtmfPt;int eventClock=dtmfClock;int ticksPerMs=eventClock/1000,minDuration=eventClock/50,minEndDuration=eventClock*160/1000;long eventTs; synchronized(sendLock){eventTs=timestamp;}long start=SystemClock.elapsedRealtime();int duration=minDuration;boolean first=true;Log.i("AP_DTMF_RTP","START event="+event+" pt="+eventPt+" clock="+eventClock+" voicePt="+pt+" ssrc="+ssrc+" timestamp="+eventTs+" endpoint="+address.getHostAddress()+":"+port);try{while(running.get()){long elapsed=SystemClock.elapsedRealtime()-start;duration=(int)Math.min(0xffff,Math.max(minDuration,elapsed*ticksPerMs));sendDtmfPacket(eventPt,event,eventTs,duration,false,first);first=false;synchronized(dtmfLock){if(dtmfStop&&elapsed>=160)break;dtmfLock.wait(50);}if(elapsed>=5000)break;}duration=(int)Math.min(0xffff,Math.max(minEndDuration,(SystemClock.elapsedRealtime()-start)*ticksPerMs));for(int i=0;i<3;i++)sendDtmfPacket(eventPt,event,eventTs,duration,true,false);Log.i("AP_DTMF_RTP","END event="+event+" pt="+eventPt+" clock="+eventClock+" duration="+duration+" packets="+dtmfPackets+" endRepeats=3");}catch(Throwable e){dtmfErrors++;Log.e("AP_DTMF_RTP","FAIL event="+event,e);}finally{synchronized(dtmfLock){dtmfEvent=-1;dtmfStop=false;}}}
 private void sendPacketRaw(byte[] p)throws Exception{socket.send(new DatagramPacket(p,p.length,address,port));}
 private void sendDtmfPacket(int eventPt,int event,long ts,int duration,boolean end,boolean mark)throws Exception{byte[] p=new byte[16];p[0]=(byte)0x80;p[1]=(byte)((mark?0x80:0)|eventPt);p[4]=(byte)(ts>>>24);p[5]=(byte)(ts>>>16);p[6]=(byte)(ts>>>8);p[7]=(byte)ts;put32(p,8,ssrc);p[12]=(byte)event;p[13]=(byte)((end?0x80:0)|10);p[14]=(byte)(duration>>>8);p[15]=(byte)duration;synchronized(sendLock){p[2]=(byte)(seq>>>8);p[3]=(byte)seq;sendPacketRaw(p);seq=(seq+1)&0xffff;}dtmfPackets++;if(dtmfPackets<=5||end)Log.i("AP_DTMF_RTP","TX event="+event+" pt="+eventPt+" seq="+(((p[2]&255)<<8)|(p[3]&255))+" timestamp="+ts+" duration="+duration+" end="+end+" marker="+mark);}
 byte[] packet(byte[] storage,int off,int len,int pt,boolean marker,int seq,long ts,long ssrc){if(len<2)throw new IllegalArgumentException("short storage");int ft=(storage[off]>>3)&15,q=(storage[off]>>2)&1,n=bits(ft),need=1+(n+7)/8;if(len<need)throw new IllegalArgumentException("short frame");byte[] out=new byte[12+(10+n+7)/8];out[0]=(byte)0x80;out[1]=(byte)((marker?0x80:0)|(pt&127));out[2]=(byte)(seq>>>8);out[3]=(byte)seq;put32(out,4,ts);put32(out,8,ssrc);int base=96;for(int i=0;i<4;i++)setBit(out,base+i,1);setBit(out,base+5,(ft>>3)&1);setBit(out,base+6,(ft>>2)&1);setBit(out,base+7,(ft>>1)&1);setBit(out,base+8,ft&1);setBit(out,base+9,q);for(int i=0;i<n;i++)setBit(out,base+10+i,bit(storage,(off+1)*8+i));return out;}
 private static void put32(byte[]b,int o,long v){b[o]=(byte)(v>>>24);b[o+1]=(byte)(v>>>16);b[o+2]=(byte)(v>>>8);b[o+3]=(byte)v;}
 private void sendFrame(byte[] data,int off,int len)throws Exception{int ft=(data[off]>>3)&15;int size=1+(bits(ft)+7)/8;if(len<size)throw new IllegalArgumentException("encoder short FT="+ft);byte[] p;int sentSeq;long sentTs;synchronized(sendLock){sentSeq=seq;sentTs=timestamp;p=packet(data,off,size,pt,marker,seq,timestamp,ssrc);sendPacketRaw(p);marker=false;seq=(seq+1)&0xffff;timestamp=(timestamp+timestampStep)&0xffffffffL;}packets++;bytes+=p.length;encodedFrames++;ftCounts[ft]++;if(packets<=3||packets%100==0)Log.i(TAG,"TX count="+packets+" bytes="+p.length+" ft="+ft+" seq="+sentSeq+" ts="+sentTs+" ssrc="+ssrc+" endpoint="+address.getHostAddress()+":"+port);}
 private void drain(MediaCodec.BufferInfo info)throws Exception{for(;;){int ix=codec.dequeueOutputBuffer(info,packets==0?10000:0);if(ix==MediaCodec.INFO_OUTPUT_FORMAT_CHANGED){Log.i(TAG,"FORMAT "+codec.getOutputFormat());continue;}if(ix<0)return;ByteBuffer b=codec.getOutputBuffer(ix);if(b!=null&&info.size>0){byte[] x=new byte[info.size];b.position(info.offset);b.get(x);for(int o=0;o<x.length;){int ft=(x[o]>>3)&15,size=1+(bits(ft)+7)/8;if(o+size>x.length)throw new IllegalArgumentException("concatenated frame short");sendFrame(x,o,size);o+=size;}}codec.releaseOutputBuffer(ix,false);}}
 private void run(){String srcName=ApMediaConfigPoc.source();int src=source(srcName),seconds=ApMediaConfigPoc.uplinkSeconds();long start=SystemClock.elapsedRealtime();String stopReason="call_lifecycle";try{if(src<0)throw new IllegalArgumentException("source="+srcName);MediaFormat f=MediaFormat.createAudioFormat(codecMime,sampleRate,1);f.setInteger(MediaFormat.KEY_BIT_RATE,bitRate);f.setInteger(MediaFormat.KEY_PRIORITY,0);codec=MediaCodec.createEncoderByType(codecMime);codec.configure(f,null,null,MediaCodec.CONFIGURE_FLAG_ENCODE);codec.start();int min=AudioRecord.getMinBufferSize(sampleRate,AudioFormat.CHANNEL_IN_MONO,AudioFormat.ENCODING_PCM_16BIT);if(min<=0)throw new IllegalStateException("minBuffer="+min);int bs=Math.max(6400,min*2);record=new AudioRecord(src,sampleRate,AudioFormat.CHANNEL_IN_MONO,AudioFormat.ENCODING_PCM_16BIT,bs);if(record.getState()!=AudioRecord.STATE_INITIALIZED)throw new IllegalStateException("uninitialized");record.startRecording();Log.i(TAG,"START source="+srcName+" seconds="+(seconds>0?Integer.toString(seconds):"unbounded")+" codec="+codec.getName()+" codecMime="+codecMime+" sampleRate="+sampleRate+" timestampStep="+timestampStep+" bitRate="+bitRate+" pt="+pt+" ssrc="+ssrc+" endpoint="+address.getHostAddress()+":"+port+" duplicateCpUplink=true rtpSend=true");byte[] pcm=new byte[bs];MediaCodec.BufferInfo info=new MediaCodec.BufferInfo();while(running.get()&&(seconds<=0||SystemClock.elapsedRealtime()-start<seconds*1000L)&&ApMediaConfigPoc.bool("ap_uplink_rtp",true)){int n=record.read(pcm,0,pcm.length);if(n<0)throw new IllegalStateException("read="+n);if(n==0)continue;pcmBytes+=n;int o=0;while(o<n){int ix=codec.dequeueInputBuffer(10000);if(ix<0){drain(info);continue;}ByteBuffer in=codec.getInputBuffer(ix);in.clear();int take=Math.min(in.remaining(),n-o);in.put(pcm,o,take);codec.queueInputBuffer(ix,0,take,System.nanoTime()/1000L,0);o+=take;drain(info);}}}catch(Throwable e){errors++;Log.e(TAG,"FAIL",e);}finally{running.set(false);AudioRecord r=record;record=null;if(r!=null){try{r.stop();}catch(Throwable ignored){}try{r.release();}catch(Throwable ignored){}}MediaCodec c=codec;codec=null;if(c!=null){try{c.stop();}catch(Throwable ignored){}try{c.release();}catch(Throwable ignored){}}Log.i(TAG,"STOP packets="+packets+" bytes="+bytes+" errors="+errors+" pcmBytes="+pcmBytes+" encodedFrames="+encodedFrames+" bitRate="+bitRate+" ftDist="+distribution(ftCounts)+" dtmfPackets="+dtmfPackets+" dtmfErrors="+dtmfErrors+" rtpSend=true");}}
}
